---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
